
- type: job
  id: MedicalBorg
  name: job-name-medical-borg
  description: job-description-medical-borg
  playTimeTracker: JobMedicalBorg
  requirements:
    - !type:CharacterOverallTimeRequirement
      min: 180000 #30 hrs - same as normal borg
    - !type:DepartmentTimeRequirement
      department: Medical
      min: 21600 #6 hrs
  canBeAntag: false
  icon: JobIconMedicalBorg
  supervisors: job-supervisors-cmo
  jobEntity: BorgChassisMedical
