- type: job
  id: TechnicalAssistant
  name: job-name-technical-assistant
  description: job-description-technical-assistant
  playTimeTracker: JobTechnicalAssistant
  antagAdvantage: 3 # DeltaV - Reduced TC: External Access + Engineering
  requirements:
  - !type:CharacterOverallTimeRequirement # DeltaV - to prevent griefers from taking the role.
      min: 3600 # 1 hours
    # - !type:DepartmentTimeRequirement # DeltaV - Removes time limit
    #   department: Engineering
    #   time: 54000 #15 hrs
    #   inverted: true # stop playing intern if you're good at engineering!
  startingGear: TechnicalAssistantGear
  icon: "JobIconTechnicalAssistant"
  supervisors: job-supervisors-engineering
  canBeAntag: false # goob mrp - shouldn't be antag, its a training role
  access:
  - Maintenance
  - Engineering
  - External

- type: startingGear
  id: TechnicalAssistantGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorYellow
    back: ClothingBackpackEngineeringFilled
    shoes: ClothingShoesBootsWork
    id: TechnicalAssistantPDA
    eyes: ClothingEyesGlassesMeson
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
    pocket2: BookEngineersHandbook
<<<<<<< HEAD
  innerClothingSkirt: ClothingUniformJumpskirtColorYellow
  satchel: ClothingBackpackSatchelEngineeringFilled
  duffelbag: ClothingBackpackDuffelEngineeringFilled
=======
  storage:
    back:
    - BoxSurvivalEngineering
>>>>>>> 3989974647 (Update time requirements for roles, and fix blueshield + ntr not spawning with survival box)
