- type: job
  id: ResearchAssistant
  name: job-name-research-assistant
  description: job-description-research-assistant
  playTimeTracker: JobResearchAssistant
  requirements:
    # - !type:DepartmentTimeRequirement # DeltaV - Removes time limit
    #   department: Science
    #   time: 54000 #15 hrs
    #   inverted: true # stop playing intern if you're good at science!
  startingGear: ResearchAssistantGear
  icon: "JobIconResearchAssistant"
  supervisors: job-supervisors-science
<<<<<<< HEAD
  canBeAntag: false # goob mrp - training role
=======
  canBeAntag: true # Goobstation - Reset back to True (Starch had set it to false)
>>>>>>> 6771ab1118b3e4bf7a702540245449e4125b0a38
  access:
  - Research
  - Maintenance

- type: startingGear
  id: ResearchAssistantGear
  subGear:
  - ScientistPlasmamanGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorWhite
    back: ClothingBackpackScienceFilled
    shoes: ClothingShoesColorWhite
    id: ResearchAssistantPDA
    ears: ClothingHeadsetScience
    pocket1: BookPsionicsGuidebook
    pocket2: BookScientistsGuidebook
  innerClothingSkirt: ClothingUniformJumpskirtColorWhite
  satchel: ClothingBackpackSatchelScienceFilled
  duffelbag: ClothingBackpackDuffelScienceFilled
