# evil gang :interrobang:

- type: antag
  id: Nukeops
  name: roles-antag-nuclear-operative-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-objective
  requirements:
  - !type:CharacterOverallTimeRequirement
    min: 36000 # Goob MRP - 10 Hours
  # Undo Starch's blatant deletion and leave comments for originals.
  # - !type:CharacterDepartmentTimeRequirement # DeltaV - Security dept time requirement
  #   department: Security
  #   min: 36000 # DeltaV - 10 hours

- type: antag
  id: NukeopsMedic
  name: roles-antag-nuclear-operative-agent-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-agent-objective
  requirements:
  - !type:CharacterOverallTimeRequirement
    min: 54000 # Goob MRP - 15 Hours
  - !type:CharacterDepartmentTimeRequirement
    department: Medical
    min: 36000 # Goob MRP - 10 Hours

- type: antag
  id: NukeopsCommander
  name: roles-antag-nuclear-operative-commander-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-commander-objective
  requirements:
  - !type:CharacterOverallTimeRequirement
    min: 108000 # Goob MRP - 30 hours
  - !type:CharacterDepartmentTimeRequirement # DeltaV - Security dept time requirement
    department: Security
    min: 18000 # Goob MRP - 5 Hours
  - !type:CharacterDepartmentTimeRequirement # DeltaV - Command dept time requirement
    department: Command
    min: 18000 # Goob MRP - 5 Hours
  # - !type:CharacterWhitelistRequirement # Undo Starch's blatant deletion instead of commenting out.


#Lone Operative Gear
- type: startingGear
  id: SyndicateLoneOperativeGearFull
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackDuffelSyndicateOperative
    mask: ClothingMaskGasSyndicate
    eyes: ClothingEyesHudSyndicate
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitSyndie
    shoes: ClothingShoesBootsCombatFilled
    id: SyndiPDA
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: BaseUplinkRadio40TC
    belt: ClothingBeltMilitaryWebbing
  innerClothingSkirt: ClothingUniformJumpskirtOperative
  satchel: ClothingBackpackDuffelSyndicateOperative
  duffelbag: ClothingBackpackDuffelSyndicateOperative
